### ISSUE TITLE
Change SDK resolution mechanism

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbrytv#174]
In the new cluster deployment SDK servers will be addressed as `lbrynet-{id}.sdk.default.svc.cluster.local` and scaled on the fly, we need to move from relying on data in the `lbrynet_servers` table to some kind of dynamic address generation.

User to SDK address resolving also needs to be changed accordingly.

**Comment by tiger5226** [comment]
I had a discussion with @andbeletsky today about this. There are some significant drawbacks with removing the database connection here. 

- We can avoid mapping users to SDKs in the database. This requires a deterministic way of assigning SDKs to users. The obvious solution here is to just take the `user_id % len(sdks)`. The problem with this approach is that this forces automatic rebalancing of ALL users. This is problematic because if we add an SDK to the cluster all SDKs will likely have to sync wallets for their newly balanced set of users because any deterministic method based on the number of SDKs(balancing) will change which SDK users are assigned too. The database solution allows this to be a controlled process for current users and automatic for new users accessing the website. We could potential minimize the cost and increase the benefit by, removing the link for users on SDK startup for its users. So as they access the site they will be loaded into another SDK(balanced). 

- In the cluster the number of SDKs that are live would be unknown without the servers table in the db. In my conversation with @andbeletsky , it is probably best to keep the table so we can ensure a deterministic assignment solution. However, managing the table along with the cluster needs to bee defined. We could create an api which adds/deletes SDKs from the db when we spin up or take down an  SDK instance. This could reside in the proxy, but we will most likely want to scale the proxy too. So it may be best to have a different microservice that handles this. This sounds like a good use case for AWS Lambda and serverless APIs. @andbeletsky will be putting some more thought into this.

**Comment by andbeletsky** [comment]
> removing the link for users on SDK startup for its users. So as they access the site they will be loaded into another SDK(balanced).

I'd like to note that no wallets are loaded on SDK startup since #138 went live.

**Comment by andybeletsky** [comment]
We're staying with static assignments for now.
